### PR TITLE
Adds Tab Removal Via CTRL+T & CTRL+W

### PR DESCRIPTION
**Pull request by jdc20181**
Issue #6

### CODE REVIEW

**Comment by jdc20181** [comment]
Effectively this will open or remove a tab depending what combo you input 

`ctrl+T` will open A a new tab and `CTRL+ W` will remove one.

**Comment by jdc20181** [comment]
Some notes to add to my code - I am going to make adjustments, apparently just "+" don't work you need `andalso`

**Comment by jdc20181** [comment]
Most of the modifications were simply due to the fact I did it out of memory, rather than formally. Apparently also the keybind was picking up the second `Elseif` so I moved one of them to the `me.keypress` and left the other with Tabcontrol, is this the best way? To accomplish yes, but I am sure there is a easier way to do it, together with less code, however, with the issue I had, it was impossible to resolve.

**Comment by jdc20181** [comment]
I have to do more adjustments, yet again it is not doing the correct behavior 😓

**Comment by DrewNaylor** [comment]
I had been very busy for the past several months so I couldn't respond; sorry about that. I figured that I could respond while updating my copyrights for 2018 to say that I'm probably not going to continue working on my web browser for the foreseeable future. I also wanted to thank you for the help you provided for my web browser project. The only reason why I'm temporarily suspending development on this project until further notice is because developing a web browser is a lot of work and it's not something I want to be spending my development effort on when working on my personal projects. On the other hand, if you need help with your browser project, I'll help if I have time, usually in the summer.

Your code is very good, so keep up the good work. I'll keep this pull request in mind in case I do come back to this project.

**Pull request closed without merging**
